name: app_news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.4.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  webfeed_plus: ^1.1.2
  webview_flutter: ^4.13.0
  xml: ^6.5.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
